/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TradeInRouteImport } from './routes/trade-in'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as InventorySlugRouteImport } from './routes/inventory.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAppointmentsRouteImport } from './routes/_authenticated/admin/appointments'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated/admin/blog'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated/admin/faqs'
import { Route as AuthenticatedAdminFinancingRouteImport } from './routes/_authenticated/admin/financing'
import { Route as AuthenticatedAdminGalleriesRouteImport } from './routes/_authenticated/admin/galleries'
import { Route as AuthenticatedAdminHomepageRouteImport } from './routes/_authenticated/admin/homepage'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin/leads'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminNavigationRouteImport } from './routes/_authenticated/admin/navigation'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin/pages'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin/services'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin/team'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin/testimonials'
import { Route as AuthenticatedAdminTradeInsRouteImport } from './routes/_authenticated/admin/trade-ins'
import { Route as AuthenticatedAdminVehiclesIndexRouteImport } from './routes/_authenticated/admin/vehicles.index'
import { Route as AuthenticatedAdminVehiclesIdRouteImport } from './routes/_authenticated/admin/vehicles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeInRoute = TradeInRouteImport.update({
  id: '/trade-in',
  path: '/trade-in',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorySlugRoute = InventorySlugRouteImport.update({
  id: '/inventory/$slug',
  path: '/inventory/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAppointmentsRoute =
  AuthenticatedAdminAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminFinancingRoute =
  AuthenticatedAdminFinancingRouteImport.update({
    id: '/financing',
    path: '/financing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGalleriesRoute =
  AuthenticatedAdminGalleriesRouteImport.update({
    id: '/galleries',
    path: '/galleries',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHomepageRoute =
  AuthenticatedAdminHomepageRouteImport.update({
    id: '/homepage',
    path: '/homepage',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminNavigationRoute =
  AuthenticatedAdminNavigationRouteImport.update({
    id: '/navigation',
    path: '/navigation',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTradeInsRoute =
  AuthenticatedAdminTradeInsRouteImport.update({
    id: '/trade-ins',
    path: '/trade-ins',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVehiclesIndexRoute =
  AuthenticatedAdminVehiclesIndexRouteImport.update({
    id: '/vehicles/',
    path: '/vehicles/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVehiclesIdRoute =
  AuthenticatedAdminVehiclesIdRouteImport.update({
    id: '/vehicles/$id',
    path: '/vehicles/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/financing': typeof FinancingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/trade-in': typeof TradeInRoute
  '/warranty': typeof WarrantyRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/inventory/$slug': typeof InventorySlugRoute
  '/blog/': typeof BlogIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/financing': typeof AuthenticatedAdminFinancingRoute
  '/admin/galleries': typeof AuthenticatedAdminGalleriesRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/navigation': typeof AuthenticatedAdminNavigationRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/trade-ins': typeof AuthenticatedAdminTradeInsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/vehicles/$id': typeof AuthenticatedAdminVehiclesIdRoute
  '/admin/vehicles/': typeof AuthenticatedAdminVehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/financing': typeof FinancingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/trade-in': typeof TradeInRoute
  '/warranty': typeof WarrantyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/inventory/$slug': typeof InventorySlugRoute
  '/blog': typeof BlogIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/financing': typeof AuthenticatedAdminFinancingRoute
  '/admin/galleries': typeof AuthenticatedAdminGalleriesRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/navigation': typeof AuthenticatedAdminNavigationRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/trade-ins': typeof AuthenticatedAdminTradeInsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/vehicles/$id': typeof AuthenticatedAdminVehiclesIdRoute
  '/admin/vehicles': typeof AuthenticatedAdminVehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/financing': typeof FinancingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/services': typeof ServicesRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/trade-in': typeof TradeInRoute
  '/warranty': typeof WarrantyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/inventory/$slug': typeof InventorySlugRoute
  '/blog/': typeof BlogIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/_authenticated/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/_authenticated/admin/financing': typeof AuthenticatedAdminFinancingRoute
  '/_authenticated/admin/galleries': typeof AuthenticatedAdminGalleriesRoute
  '/_authenticated/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/navigation': typeof AuthenticatedAdminNavigationRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/trade-ins': typeof AuthenticatedAdminTradeInsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/vehicles/$id': typeof AuthenticatedAdminVehiclesIdRoute
  '/_authenticated/admin/vehicles/': typeof AuthenticatedAdminVehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/financing'
    | '/privacy-policy'
    | '/refund-policy'
    | '/services'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/trade-in'
    | '/warranty'
    | '/admin'
    | '/blog/$slug'
    | '/inventory/$slug'
    | '/blog/'
    | '/inventory/'
    | '/admin/appointments'
    | '/admin/blog'
    | '/admin/faqs'
    | '/admin/financing'
    | '/admin/galleries'
    | '/admin/homepage'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/trade-ins'
    | '/admin/'
    | '/admin/vehicles/$id'
    | '/admin/vehicles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/financing'
    | '/privacy-policy'
    | '/refund-policy'
    | '/services'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/trade-in'
    | '/warranty'
    | '/blog/$slug'
    | '/inventory/$slug'
    | '/blog'
    | '/inventory'
    | '/admin/appointments'
    | '/admin/blog'
    | '/admin/faqs'
    | '/admin/financing'
    | '/admin/galleries'
    | '/admin/homepage'
    | '/admin/leads'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/trade-ins'
    | '/admin'
    | '/admin/vehicles/$id'
    | '/admin/vehicles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/compare'
    | '/contact'
    | '/faq'
    | '/financing'
    | '/privacy-policy'
    | '/refund-policy'
    | '/services'
    | '/team'
    | '/terms'
    | '/testimonials'
    | '/trade-in'
    | '/warranty'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/inventory/$slug'
    | '/blog/'
    | '/inventory/'
    | '/_authenticated/admin/appointments'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/faqs'
    | '/_authenticated/admin/financing'
    | '/_authenticated/admin/galleries'
    | '/_authenticated/admin/homepage'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/navigation'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/team'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/trade-ins'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/vehicles/$id'
    | '/_authenticated/admin/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FinancingRoute: typeof FinancingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ServicesRoute: typeof ServicesRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TradeInRoute: typeof TradeInRoute
  WarrantyRoute: typeof WarrantyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  InventorySlugRoute: typeof InventorySlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-in': {
      id: '/trade-in'
      path: '/trade-in'
      fullPath: '/trade-in'
      preLoaderRoute: typeof TradeInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$slug': {
      id: '/inventory/$slug'
      path: '/inventory/$slug'
      fullPath: '/inventory/$slug'
      preLoaderRoute: typeof InventorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/appointments': {
      id: '/_authenticated/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AuthenticatedAdminAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/faqs': {
      id: '/_authenticated/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/financing': {
      id: '/_authenticated/admin/financing'
      path: '/financing'
      fullPath: '/admin/financing'
      preLoaderRoute: typeof AuthenticatedAdminFinancingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/galleries': {
      id: '/_authenticated/admin/galleries'
      path: '/galleries'
      fullPath: '/admin/galleries'
      preLoaderRoute: typeof AuthenticatedAdminGalleriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/homepage': {
      id: '/_authenticated/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AuthenticatedAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/navigation': {
      id: '/_authenticated/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AuthenticatedAdminNavigationRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/trade-ins': {
      id: '/_authenticated/admin/trade-ins'
      path: '/trade-ins'
      fullPath: '/admin/trade-ins'
      preLoaderRoute: typeof AuthenticatedAdminTradeInsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/vehicles/': {
      id: '/_authenticated/admin/vehicles/'
      path: '/vehicles'
      fullPath: '/admin/vehicles/'
      preLoaderRoute: typeof AuthenticatedAdminVehiclesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/vehicles/$id': {
      id: '/_authenticated/admin/vehicles/$id'
      path: '/vehicles/$id'
      fullPath: '/admin/vehicles/$id'
      preLoaderRoute: typeof AuthenticatedAdminVehiclesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAppointmentsRoute: typeof AuthenticatedAdminAppointmentsRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRoute
  AuthenticatedAdminFinancingRoute: typeof AuthenticatedAdminFinancingRoute
  AuthenticatedAdminGalleriesRoute: typeof AuthenticatedAdminGalleriesRoute
  AuthenticatedAdminHomepageRoute: typeof AuthenticatedAdminHomepageRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminNavigationRoute: typeof AuthenticatedAdminNavigationRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminTradeInsRoute: typeof AuthenticatedAdminTradeInsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminVehiclesIdRoute: typeof AuthenticatedAdminVehiclesIdRoute
  AuthenticatedAdminVehiclesIndexRoute: typeof AuthenticatedAdminVehiclesIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAppointmentsRoute: AuthenticatedAdminAppointmentsRoute,
    AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
    AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRoute,
    AuthenticatedAdminFinancingRoute: AuthenticatedAdminFinancingRoute,
    AuthenticatedAdminGalleriesRoute: AuthenticatedAdminGalleriesRoute,
    AuthenticatedAdminHomepageRoute: AuthenticatedAdminHomepageRoute,
    AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
    AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
    AuthenticatedAdminNavigationRoute: AuthenticatedAdminNavigationRoute,
    AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
    AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
    AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
    AuthenticatedAdminTradeInsRoute: AuthenticatedAdminTradeInsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminVehiclesIdRoute: AuthenticatedAdminVehiclesIdRoute,
    AuthenticatedAdminVehiclesIndexRoute: AuthenticatedAdminVehiclesIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FinancingRoute: FinancingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ServicesRoute: ServicesRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  TradeInRoute: TradeInRoute,
  WarrantyRoute: WarrantyRoute,
  BlogSlugRoute: BlogSlugRoute,
  InventorySlugRoute: InventorySlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
